/** @type {import('stylelint').Config} */
export default {
  extends: ["stylelint-config-standard-scss"],
  plugins: ["stylelint-order", "@stylistic/stylelint-plugin"],

  overrides: [
    {
      files: ["**/*.vue"],
      customSyntax: "postcss-html",
    },
    {
      files: ["**/*.scss"],
      customSyntax: "postcss-scss",
    },
  ],

  rules: {
    "scss/dollar-variable-pattern": "^evora-[a-z0-9-]+$",

    "order/properties-order": [
      [
        "all",
        "position",
        "inset",
        "inset-block",
        "inset-inline",
        "top",
        "right",
        "bottom",
        "left",
        "z-index",

        "display",
        "flex",
        "flex-direction",
        "flex-wrap",
        "flex-grow",
        "flex-shrink",
        "flex-basis",
        "justify-content",
        "align-items",
        "align-content",
        "align-self",
        "gap",
        "row-gap",
        "column-gap",

        "grid",
        "grid-template",
        "grid-template-rows",
        "grid-template-columns",
        "grid-template-areas",
        "grid-area",
        "grid-row",
        "grid-row-start",
        "grid-row-end",
        "grid-column",
        "grid-column-start",
        "grid-column-end",
        "place-items",
        "place-content",
        "place-self",

        "box-sizing",
        "width",
        "min-width",
        "max-width",
        "height",
        "min-height",
        "max-height",
        "aspect-ratio",

        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",

        "overflow",
        "overflow-x",
        "overflow-y",
        "object-fit",
        "object-position",
        "clip",
        "clear",
        "float",

        "border",
        "border-width",
        "border-style",
        "border-color",
        "border-top",
        "border-right",
        "border-bottom",
        "border-left",
        "border-radius",
        "outline",
        "outline-offset",

        "background",
        "background-color",
        "background-image",
        "background-size",
        "background-position",
        "background-repeat",
        "background-attachment",
        "color",
        "opacity",

        "box-shadow",
        "filter",
        "backdrop-filter",

        "font",
        "font-family",
        "font-size",
        "font-style",
        "font-weight",
        "letter-spacing",
        "line-height",
        "text-align",
        "text-decoration",
        "text-transform",
        "white-space",
        "word-break",

        "transition",
        "transition-property",
        "transition-duration",
        "transition-timing-function",
        "transition-delay",
        "animation",
        "animation-name",
        "animation-duration",
        "animation-fill-mode",
        "animation-timing-function",
        "animation-delay",
        "animation-iteration-count",
        "animation-direction",

        "transform",
        "transform-origin",
        "will-change",

        "cursor",
        "pointer-events",
        "user-select",
        "touch-action",
        "resize",

        "visibility",
        "content",
        "appearance",
        "quotes",

        "--",
      ],
      {
        unspecified: "bottomAlphabetical",
      },
    ],

    // Enforce multi-line style blocks (disallow one-line styles)
    // Note: stylistic rules moved out of core in Stylelint v16
    "@stylistic/block-opening-brace-newline-after": "always",
    "@stylistic/block-closing-brace-newline-before": "always",
    "@stylistic/declaration-block-semicolon-newline-after": "always",
    "@stylistic/selector-list-comma-newline-after": "always",
    // Indentation for declarations/selectors
    "@stylistic/indentation": 2,
    // Disallow single-line declaration blocks entirely
    "declaration-block-single-line-max-declarations": 0,

    "declaration-block-no-duplicate-properties": true,
    "property-no-unknown": true,
    "unit-no-unknown": true,
    "color-no-invalid-hex": true,
    "function-name-case": "lower",
    "no-invalid-position-at-import-rule": true,

    "no-descending-specificity": null,
    "no-empty-source": null,
    "color-function-notation": null,
    "selector-class-pattern": null,
  },

  ignoreFiles: ["**/dist/**", "**/node_modules/**"],
};
