name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup Yarn (Corepack)
        run: |
          corepack enable
          corepack prepare yarn@4.9.4 --activate
          yarn --version

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Generate (strict)
        run: |
          STRICT=1 yarn generate

      - name: Build
        run: yarn build

      - name: Types
        run: yarn types
