name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-vue:
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Setup Yarn (Corepack)
        run: |
          corepack enable
          corepack prepare yarn@4.9.4 --activate
          yarn --version
      - run: yarn install --immutable
      - run: node tools/generate-icons.mjs --pkg packages/vue
      - run: yarn workspace @evora-ui/icons-vue run build
      - run: yarn workspace @evora-ui/icons-vue run types
      - name: Include LICENSE in package
        run: |
          cp -f LICENSE packages/vue/
      - run: npm publish --access public --provenance
        working-directory: packages/vue
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
